version: '3'
services:
  service:
    build: .
    ports:
      - "7002:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/usr/src/app/config
    container_name: afdian-sponsor-manage-service
    restart: always
